import { Link } from "@tanstack/react-router";
import { ArrowRight, Car, Check, CircleHelp, MapPin, MessageCircle, Mountain, Navigation, Phone, Route, ShieldCheck } from "lucide-react";
import heroImage from "@/assets/himalayan-road-hero.jpg";
import carImage from "@/assets/taxi-sedan.jpg";
import { business, charDhams, formatPrice, rateTerms, routePages, services, vehicles } from "@/config/business";
import { bookingMessage, whatsappUrl } from "@/lib/booking";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { SiteLayout } from "./layout";
import { RateTable } from "./home";

export function PageHero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}) { return <section className="relative isolate overflow-hidden bg-primary py-20 text-primary-foreground"><img src={heroImage} alt="Mountain road in the Uttarakhand Himalayas" width={1600} height={1000} loading="lazy" className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-page-overlay"/><div className="site-container"><p className="mb-3 text-xs font-bold uppercase tracking-widest text-accent">{eyebrow}</p><h1 className="max-w-3xl font-display text-4xl font-extrabold leading-tight sm:text-5xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-primary-foreground/80 sm:text-lg">{description}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><a href={whatsappUrl(bookingMessage())} target="_blank" rel="noreferrer"><MessageCircle/>Book on WhatsApp</a></Button><Button asChild size="lg" variant="light"><a href={`tel:${business.phone}`}><Phone/>Call {business.phoneDisplay}</a></Button></div></div></section>; }

const serviceCopy = {
  taxi: { eyebrow:"Kotdwar taxi service", title:"Reliable local taxi service in Kotdwar", description:"Book clean, comfortable taxi travel for local journeys, hotel transfers, railway trips, and nearby destinations.", points:["Point-to-point local travel","Flexible pickup within Kotdwar","Sedan and SUV options","Direct phone and WhatsApp booking"] },
  outstation: { eyebrow:"Outstation travel", title:"Outstation taxi from Kotdwar", description:"Travel across Uttarakhand, Delhi NCR, and nearby destinations with transparent one-way fares and reliable drivers.", points:["One-way and round-trip options","Experienced hill-road drivers","Clear route rates","Doorstep pickup"] },
  airport: { eyebrow:"Airport & station transfers", title:"Airport taxi from Kotdwar", description:"Plan direct transfers to Delhi Airport, Dehradun Airport, and major railway stations with convenient pickup.", points:["Planned pickup times","Space for passengers and luggage","Delhi Airport one-way rates available","Early morning and late-night trips"] },
} as const;
export function ServicePage({type}:{type:keyof typeof serviceCopy}) { const page=serviceCopy[type]; return <SiteLayout><PageHero {...page}/><section className="section"><div className="site-container grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="section-eyebrow text-left">What to expect</p><h2 className="section-title text-left">A comfortable taxi, planned around you</h2><div className="mt-6 grid gap-3">{page.points.map(x=><p key={x} className="flex items-center gap-3 rounded-xl border bg-card p-4 font-semibold"><Check className="size-5 text-accent"/>{x}</p>)}</div></div><img src={carImage} alt="White sedan used for Anand Tour and Travel taxi journeys" width={1200} height={700} loading="lazy" className="w-full rounded-xl border bg-card object-cover"/></div></section>{type==="outstation"&&<RateTable/>}<SimpleCTA /></SiteLayout>; }

export function CharDhamPage() { return <SiteLayout><PageHero eyebrow="Char Dham Yatra" title="Taxi service for Uttarakhand's sacred journey" description="Plan Kedarnath, Badrinath, Gangotri, or Yamunotri travel from Kotdwar with direct assistance and a suitable vehicle."/><section className="section"><div className="site-container grid gap-5 sm:grid-cols-2">{charDhams.map((dham,index)=><article key={dham.name} className="rounded-xl border bg-card p-6 shadow-sm"><span className="grid size-12 place-items-center rounded-lg bg-primary text-primary-foreground"><Mountain/></span><p className="mt-5 text-xs font-bold uppercase tracking-widest text-accent">Dham {String(index+1).padStart(2,"0")}</p><h2 className="mt-1 font-display text-2xl font-bold">{dham.name}</h2><p className="mt-3 leading-7 text-muted-foreground">{dham.description}</p><Button asChild className="mt-6"><a href={whatsappUrl(`Hello ${business.name}, I would like to plan a ${dham.name} taxi journey.`)} target="_blank" rel="noreferrer"><MessageCircle/>Ask about {dham.name}</a></Button></article>)}</div><div className="site-container mt-8"><div className="rounded-xl bg-highlight p-6"><h3 className="font-display text-xl font-bold">Important fare terms</h3><ul className="mt-4 grid gap-2 sm:grid-cols-3">{rateTerms.map(x=><li key={x} className="flex gap-2 text-sm"><Check className="size-4 shrink-0 text-accent"/>{x}</li>)}</ul></div></div></section><SimpleCTA/></SiteLayout>; }

export function RoutePage({pageKey}:{pageKey:keyof typeof routePages}) { const page=routePages[pageKey]; return <SiteLayout><PageHero eyebrow="One-way taxi from Kotdwar" title={`Kotdwar to ${page.destination} Taxi`} description={page.intro}/><section className="section"><div className="site-container"><div className="grid gap-5 md:grid-cols-2">{[{name:"Swift Dzire",seats:"4 Seater Sedan",price:page.dzire},{name:"Maruti Ertiga",seats:"6+1 Seater SUV",price:page.ertiga}].map(item=><article key={item.name} className="rounded-xl border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><span className="grid size-12 place-items-center rounded-lg bg-secondary text-primary"><Car/></span><div className="text-right"><small className="text-muted-foreground">One-way fare</small><strong className="block font-display text-3xl text-accent">{formatPrice(item.price)}</strong></div></div><h2 className="mt-6 font-display text-xl font-bold">{item.name}</h2><p className="text-sm text-muted-foreground">{item.seats}</p><Button asChild size="lg" className="mt-6 w-full"><a href={whatsappUrl(bookingMessage(page.destination,item.name))} target="_blank" rel="noreferrer"><MessageCircle/>Book this taxi</a></Button></article>)}</div><div className="mt-6 rounded-xl border bg-highlight p-6"><h2 className="font-display text-xl font-bold">Fare terms</h2><ul className="mt-4 grid gap-3 sm:grid-cols-3">{rateTerms.map(x=><li key={x} className="flex gap-2 text-sm font-medium"><Check className="size-4 shrink-0 text-accent"/>{x}</li>)}</ul></div></div></section><SimpleCTA/></SiteLayout>; }

export function VehiclesPage() { return <SiteLayout><PageHero eyebrow="Our fleet" title="Choose the right taxi for your journey" description="Compare our listed sedan and SUV options for local, outstation, and hill travel from Kotdwar."/><section className="section"><div className="site-container grid gap-5 md:grid-cols-2">{vehicles.map(v=><article key={v.id} className="overflow-hidden rounded-xl border bg-card shadow-sm"><img src={carImage} alt={`White ${v.name} style taxi for ${v.category} travel`} width={1200} height={700} loading="lazy" className="aspect-[16/9] w-full object-cover"/><div className="p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-2xl font-bold">{v.name}</h2><p className="text-sm text-muted-foreground">{v.category}</p></div><strong className="text-accent">{v.perKm}</strong></div><p className="mt-4 leading-7 text-muted-foreground">{v.description}</p><Button asChild className="mt-6"><a href={whatsappUrl(bookingMessage(undefined,v.name))} target="_blank" rel="noreferrer">Book {v.name}<ArrowRight/></a></Button></div></article>)}</div></section><RateTable/></SiteLayout>; }

export function AboutPage() { return <SiteLayout><PageHero eyebrow="About us" title="Your journey is our responsibility" description="Anand Tour & Travel is a customer-focused taxi service based in Kotdwar, serving local journeys, outstation routes, and Uttarakhand pilgrimage travel."/><section className="section"><div className="site-container grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="rounded-xl bg-primary p-8 text-primary-foreground"><Mountain className="size-12 text-accent"/><p className="mt-8 text-sm uppercase tracking-widest text-accent">Based in</p><h2 className="mt-2 font-display text-3xl font-bold">{business.location}</h2><p className="mt-4 text-primary-foreground/70">Direct bookings. Clear communication. Travel planned around your route.</p></div><div><p className="section-eyebrow text-left">Our approach</p><h2 className="section-title text-left">Practical, dependable taxi travel</h2><p className="mt-5 leading-8 text-muted-foreground">We focus on the things that matter during a road journey: a clean vehicle, an experienced driver, timely pickup, and clear fare communication. Whether you are visiting Lansdowne, heading to Delhi Airport, or planning a Char Dham journey, you can contact us directly for a suitable taxi plan.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Safe & reliable","Experienced hill drivers","Clean & comfortable","24/7 support"].map(x=><p key={x} className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-5 text-accent"/>{x}</p>)}</div></div></div></section></SiteLayout>; }

export function ContactPage() { return <SiteLayout><PageHero eyebrow="Contact" title="Book your taxi directly" description="Call or WhatsApp Anand Tour & Travel for availability, trip planning, and a confirmed fare."/><section className="section"><div className="site-container grid gap-5 md:grid-cols-3"><ContactCard icon={Phone} title="Call us" text={business.phoneDisplay} href={`tel:${business.phone}`}/><ContactCard icon={MessageCircle} title="WhatsApp" text="Start a booking enquiry" href={whatsappUrl(bookingMessage())}/><ContactCard icon={MapPin} title="Location" text={business.location}/></div><div className="mt-6 grid min-h-72 place-items-center rounded-xl border border-dashed bg-secondary text-center"><div><MapPin className="mx-auto size-10 text-accent"/><h2 className="mt-4 font-display text-xl font-bold">Google Maps placeholder</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">The exact map pin can be connected later without changing the booking experience.</p></div></div></section></SiteLayout>; }
function ContactCard({icon:Icon,title,text,href}:{icon:typeof Phone;title:string;text:string;href?:string}) { const content=<><Icon className="size-8 text-accent"/><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{text}</p></>; return href?<a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className="rounded-xl border bg-card p-6 shadow-sm">{content}</a>:<div className="rounded-xl border bg-card p-6 shadow-sm">{content}</div>; }

const faqs = [
  ["How do I book a taxi?",`Call ${business.phoneDisplay} or use any WhatsApp booking button and share your pickup, destination, date, passengers, and preferred vehicle.`],
  ["Are the route rates one way?","Yes. The displayed route rates are one-way fares from Kotdwar for the listed vehicle."],
  ["What charges are extra?","Toll, parking, and state tax are extra. A ₹300 night charge applies from 10 PM to 5 AM."],
  ["What applies to round trips?","For round trips, the customer arranges or covers the driver's food and stay."],
  ["Which vehicles can I request?","Booking choices include Dzire Sedan, Ertiga SUV, Innova Crysta, and Tempo Traveller. Listed table rates are available for Swift Dzire and Maruti Ertiga."],
  ["Do you provide Char Dham taxi service?","Yes. You can inquire about travel for Kedarnath, Badrinath, Gangotri, and Yamunotri."],
];
export function FaqPage() { return <SiteLayout><PageHero eyebrow="Frequently asked questions" title="Taxi booking questions, answered" description="Find clear information about fares, vehicles, extra charges, and how to book."/><section className="section"><div className="site-container max-w-3xl"><Accordion type="single" collapsible className="space-y-3">{faqs.map(([q,a],i)=><AccordionItem value={`item-${i}`} key={q} className="rounded-xl border bg-card px-5"><AccordionTrigger className="text-left font-display font-bold"><span className="flex items-center gap-3"><CircleHelp className="size-5 shrink-0 text-accent"/>{q}</span></AccordionTrigger><AccordionContent className="pl-8 leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section><SimpleCTA/></SiteLayout>; }

function SimpleCTA() { return <section className="bg-secondary py-12"><div className="site-container grid gap-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="section-eyebrow text-left">Ready to travel?</p><h2 className="font-display text-2xl font-bold">Tell us where you want to go.</h2></div><Button asChild size="lg"><a href={whatsappUrl(bookingMessage())} target="_blank" rel="noreferrer"><MessageCircle/>Get fare on WhatsApp</a></Button></div></section>; }
