/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AirportTaxiRouteImport } from './routes/airport-taxi'
import { Route as CharDhamYatraRouteImport } from './routes/char-dham-yatra'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KotdwarToBadrinathTaxiRouteImport } from './routes/kotdwar-to-badrinath-taxi'
import { Route as KotdwarToDehradunTaxiRouteImport } from './routes/kotdwar-to-dehradun-taxi'
import { Route as KotdwarToDelhiTaxiRouteImport } from './routes/kotdwar-to-delhi-taxi'
import { Route as KotdwarToGangotriTaxiRouteImport } from './routes/kotdwar-to-gangotri-taxi'
import { Route as KotdwarToHaridwarTaxiRouteImport } from './routes/kotdwar-to-haridwar-taxi'
import { Route as KotdwarToJimCorbettTaxiRouteImport } from './routes/kotdwar-to-jim-corbett-taxi'
import { Route as KotdwarToKedarnathTaxiRouteImport } from './routes/kotdwar-to-kedarnath-taxi'
import { Route as KotdwarToLansdowneTaxiRouteImport } from './routes/kotdwar-to-lansdowne-taxi'
import { Route as KotdwarToMussoorieTaxiRouteImport } from './routes/kotdwar-to-mussoorie-taxi'
import { Route as KotdwarToNainitalTaxiRouteImport } from './routes/kotdwar-to-nainital-taxi'
import { Route as KotdwarToRishikeshTaxiRouteImport } from './routes/kotdwar-to-rishikesh-taxi'
import { Route as KotdwarToYamunotriTaxiRouteImport } from './routes/kotdwar-to-yamunotri-taxi'
import { Route as OutstationTaxiRouteImport } from './routes/outstation-taxi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TaxiServiceRouteImport } from './routes/taxi-service'
import { Route as VehiclesRouteImport } from './routes/vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportTaxiRoute = AirportTaxiRouteImport.update({
  id: '/airport-taxi',
  path: '/airport-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const CharDhamYatraRoute = CharDhamYatraRouteImport.update({
  id: '/char-dham-yatra',
  path: '/char-dham-yatra',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToBadrinathTaxiRoute = KotdwarToBadrinathTaxiRouteImport.update({
  id: '/kotdwar-to-badrinath-taxi',
  path: '/kotdwar-to-badrinath-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToDehradunTaxiRoute = KotdwarToDehradunTaxiRouteImport.update({
  id: '/kotdwar-to-dehradun-taxi',
  path: '/kotdwar-to-dehradun-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToDelhiTaxiRoute = KotdwarToDelhiTaxiRouteImport.update({
  id: '/kotdwar-to-delhi-taxi',
  path: '/kotdwar-to-delhi-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToGangotriTaxiRoute = KotdwarToGangotriTaxiRouteImport.update({
  id: '/kotdwar-to-gangotri-taxi',
  path: '/kotdwar-to-gangotri-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToHaridwarTaxiRoute = KotdwarToHaridwarTaxiRouteImport.update({
  id: '/kotdwar-to-haridwar-taxi',
  path: '/kotdwar-to-haridwar-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToJimCorbettTaxiRoute = KotdwarToJimCorbettTaxiRouteImport.update({
  id: '/kotdwar-to-jim-corbett-taxi',
  path: '/kotdwar-to-jim-corbett-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToKedarnathTaxiRoute = KotdwarToKedarnathTaxiRouteImport.update({
  id: '/kotdwar-to-kedarnath-taxi',
  path: '/kotdwar-to-kedarnath-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToLansdowneTaxiRoute = KotdwarToLansdowneTaxiRouteImport.update({
  id: '/kotdwar-to-lansdowne-taxi',
  path: '/kotdwar-to-lansdowne-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToMussoorieTaxiRoute = KotdwarToMussoorieTaxiRouteImport.update({
  id: '/kotdwar-to-mussoorie-taxi',
  path: '/kotdwar-to-mussoorie-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToNainitalTaxiRoute = KotdwarToNainitalTaxiRouteImport.update({
  id: '/kotdwar-to-nainital-taxi',
  path: '/kotdwar-to-nainital-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToRishikeshTaxiRoute = KotdwarToRishikeshTaxiRouteImport.update({
  id: '/kotdwar-to-rishikesh-taxi',
  path: '/kotdwar-to-rishikesh-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const KotdwarToYamunotriTaxiRoute = KotdwarToYamunotriTaxiRouteImport.update({
  id: '/kotdwar-to-yamunotri-taxi',
  path: '/kotdwar-to-yamunotri-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const OutstationTaxiRoute = OutstationTaxiRouteImport.update({
  id: '/outstation-taxi',
  path: '/outstation-taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiServiceRoute = TaxiServiceRouteImport.update({
  id: '/taxi-service',
  path: '/taxi-service',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/airport-taxi': typeof AirportTaxiRoute
  '/char-dham-yatra': typeof CharDhamYatraRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/kotdwar-to-badrinath-taxi': typeof KotdwarToBadrinathTaxiRoute
  '/kotdwar-to-dehradun-taxi': typeof KotdwarToDehradunTaxiRoute
  '/kotdwar-to-delhi-taxi': typeof KotdwarToDelhiTaxiRoute
  '/kotdwar-to-gangotri-taxi': typeof KotdwarToGangotriTaxiRoute
  '/kotdwar-to-haridwar-taxi': typeof KotdwarToHaridwarTaxiRoute
  '/kotdwar-to-jim-corbett-taxi': typeof KotdwarToJimCorbettTaxiRoute
  '/kotdwar-to-kedarnath-taxi': typeof KotdwarToKedarnathTaxiRoute
  '/kotdwar-to-lansdowne-taxi': typeof KotdwarToLansdowneTaxiRoute
  '/kotdwar-to-mussoorie-taxi': typeof KotdwarToMussoorieTaxiRoute
  '/kotdwar-to-nainital-taxi': typeof KotdwarToNainitalTaxiRoute
  '/kotdwar-to-rishikesh-taxi': typeof KotdwarToRishikeshTaxiRoute
  '/kotdwar-to-yamunotri-taxi': typeof KotdwarToYamunotriTaxiRoute
  '/outstation-taxi': typeof OutstationTaxiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taxi-service': typeof TaxiServiceRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/airport-taxi': typeof AirportTaxiRoute
  '/char-dham-yatra': typeof CharDhamYatraRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/kotdwar-to-badrinath-taxi': typeof KotdwarToBadrinathTaxiRoute
  '/kotdwar-to-dehradun-taxi': typeof KotdwarToDehradunTaxiRoute
  '/kotdwar-to-delhi-taxi': typeof KotdwarToDelhiTaxiRoute
  '/kotdwar-to-gangotri-taxi': typeof KotdwarToGangotriTaxiRoute
  '/kotdwar-to-haridwar-taxi': typeof KotdwarToHaridwarTaxiRoute
  '/kotdwar-to-jim-corbett-taxi': typeof KotdwarToJimCorbettTaxiRoute
  '/kotdwar-to-kedarnath-taxi': typeof KotdwarToKedarnathTaxiRoute
  '/kotdwar-to-lansdowne-taxi': typeof KotdwarToLansdowneTaxiRoute
  '/kotdwar-to-mussoorie-taxi': typeof KotdwarToMussoorieTaxiRoute
  '/kotdwar-to-nainital-taxi': typeof KotdwarToNainitalTaxiRoute
  '/kotdwar-to-rishikesh-taxi': typeof KotdwarToRishikeshTaxiRoute
  '/kotdwar-to-yamunotri-taxi': typeof KotdwarToYamunotriTaxiRoute
  '/outstation-taxi': typeof OutstationTaxiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taxi-service': typeof TaxiServiceRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/airport-taxi': typeof AirportTaxiRoute
  '/char-dham-yatra': typeof CharDhamYatraRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/kotdwar-to-badrinath-taxi': typeof KotdwarToBadrinathTaxiRoute
  '/kotdwar-to-dehradun-taxi': typeof KotdwarToDehradunTaxiRoute
  '/kotdwar-to-delhi-taxi': typeof KotdwarToDelhiTaxiRoute
  '/kotdwar-to-gangotri-taxi': typeof KotdwarToGangotriTaxiRoute
  '/kotdwar-to-haridwar-taxi': typeof KotdwarToHaridwarTaxiRoute
  '/kotdwar-to-jim-corbett-taxi': typeof KotdwarToJimCorbettTaxiRoute
  '/kotdwar-to-kedarnath-taxi': typeof KotdwarToKedarnathTaxiRoute
  '/kotdwar-to-lansdowne-taxi': typeof KotdwarToLansdowneTaxiRoute
  '/kotdwar-to-mussoorie-taxi': typeof KotdwarToMussoorieTaxiRoute
  '/kotdwar-to-nainital-taxi': typeof KotdwarToNainitalTaxiRoute
  '/kotdwar-to-rishikesh-taxi': typeof KotdwarToRishikeshTaxiRoute
  '/kotdwar-to-yamunotri-taxi': typeof KotdwarToYamunotriTaxiRoute
  '/outstation-taxi': typeof OutstationTaxiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taxi-service': typeof TaxiServiceRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/airport-taxi'
    | '/char-dham-yatra'
    | '/contact'
    | '/faq'
    | '/kotdwar-to-badrinath-taxi'
    | '/kotdwar-to-dehradun-taxi'
    | '/kotdwar-to-delhi-taxi'
    | '/kotdwar-to-gangotri-taxi'
    | '/kotdwar-to-haridwar-taxi'
    | '/kotdwar-to-jim-corbett-taxi'
    | '/kotdwar-to-kedarnath-taxi'
    | '/kotdwar-to-lansdowne-taxi'
    | '/kotdwar-to-mussoorie-taxi'
    | '/kotdwar-to-nainital-taxi'
    | '/kotdwar-to-rishikesh-taxi'
    | '/kotdwar-to-yamunotri-taxi'
    | '/outstation-taxi'
    | '/sitemap.xml'
    | '/taxi-service'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/airport-taxi'
    | '/char-dham-yatra'
    | '/contact'
    | '/faq'
    | '/kotdwar-to-badrinath-taxi'
    | '/kotdwar-to-dehradun-taxi'
    | '/kotdwar-to-delhi-taxi'
    | '/kotdwar-to-gangotri-taxi'
    | '/kotdwar-to-haridwar-taxi'
    | '/kotdwar-to-jim-corbett-taxi'
    | '/kotdwar-to-kedarnath-taxi'
    | '/kotdwar-to-lansdowne-taxi'
    | '/kotdwar-to-mussoorie-taxi'
    | '/kotdwar-to-nainital-taxi'
    | '/kotdwar-to-rishikesh-taxi'
    | '/kotdwar-to-yamunotri-taxi'
    | '/outstation-taxi'
    | '/sitemap.xml'
    | '/taxi-service'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/airport-taxi'
    | '/char-dham-yatra'
    | '/contact'
    | '/faq'
    | '/kotdwar-to-badrinath-taxi'
    | '/kotdwar-to-dehradun-taxi'
    | '/kotdwar-to-delhi-taxi'
    | '/kotdwar-to-gangotri-taxi'
    | '/kotdwar-to-haridwar-taxi'
    | '/kotdwar-to-jim-corbett-taxi'
    | '/kotdwar-to-kedarnath-taxi'
    | '/kotdwar-to-lansdowne-taxi'
    | '/kotdwar-to-mussoorie-taxi'
    | '/kotdwar-to-nainital-taxi'
    | '/kotdwar-to-rishikesh-taxi'
    | '/kotdwar-to-yamunotri-taxi'
    | '/outstation-taxi'
    | '/sitemap.xml'
    | '/taxi-service'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AirportTaxiRoute: typeof AirportTaxiRoute
  CharDhamYatraRoute: typeof CharDhamYatraRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  KotdwarToBadrinathTaxiRoute: typeof KotdwarToBadrinathTaxiRoute
  KotdwarToDehradunTaxiRoute: typeof KotdwarToDehradunTaxiRoute
  KotdwarToDelhiTaxiRoute: typeof KotdwarToDelhiTaxiRoute
  KotdwarToGangotriTaxiRoute: typeof KotdwarToGangotriTaxiRoute
  KotdwarToHaridwarTaxiRoute: typeof KotdwarToHaridwarTaxiRoute
  KotdwarToJimCorbettTaxiRoute: typeof KotdwarToJimCorbettTaxiRoute
  KotdwarToKedarnathTaxiRoute: typeof KotdwarToKedarnathTaxiRoute
  KotdwarToLansdowneTaxiRoute: typeof KotdwarToLansdowneTaxiRoute
  KotdwarToMussoorieTaxiRoute: typeof KotdwarToMussoorieTaxiRoute
  KotdwarToNainitalTaxiRoute: typeof KotdwarToNainitalTaxiRoute
  KotdwarToRishikeshTaxiRoute: typeof KotdwarToRishikeshTaxiRoute
  KotdwarToYamunotriTaxiRoute: typeof KotdwarToYamunotriTaxiRoute
  OutstationTaxiRoute: typeof OutstationTaxiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaxiServiceRoute: typeof TaxiServiceRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-taxi': {
      id: '/airport-taxi'
      path: '/airport-taxi'
      fullPath: '/airport-taxi'
      preLoaderRoute: typeof AirportTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/char-dham-yatra': {
      id: '/char-dham-yatra'
      path: '/char-dham-yatra'
      fullPath: '/char-dham-yatra'
      preLoaderRoute: typeof CharDhamYatraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-badrinath-taxi': {
      id: '/kotdwar-to-badrinath-taxi'
      path: '/kotdwar-to-badrinath-taxi'
      fullPath: '/kotdwar-to-badrinath-taxi'
      preLoaderRoute: typeof KotdwarToBadrinathTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-dehradun-taxi': {
      id: '/kotdwar-to-dehradun-taxi'
      path: '/kotdwar-to-dehradun-taxi'
      fullPath: '/kotdwar-to-dehradun-taxi'
      preLoaderRoute: typeof KotdwarToDehradunTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-delhi-taxi': {
      id: '/kotdwar-to-delhi-taxi'
      path: '/kotdwar-to-delhi-taxi'
      fullPath: '/kotdwar-to-delhi-taxi'
      preLoaderRoute: typeof KotdwarToDelhiTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-gangotri-taxi': {
      id: '/kotdwar-to-gangotri-taxi'
      path: '/kotdwar-to-gangotri-taxi'
      fullPath: '/kotdwar-to-gangotri-taxi'
      preLoaderRoute: typeof KotdwarToGangotriTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-haridwar-taxi': {
      id: '/kotdwar-to-haridwar-taxi'
      path: '/kotdwar-to-haridwar-taxi'
      fullPath: '/kotdwar-to-haridwar-taxi'
      preLoaderRoute: typeof KotdwarToHaridwarTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-jim-corbett-taxi': {
      id: '/kotdwar-to-jim-corbett-taxi'
      path: '/kotdwar-to-jim-corbett-taxi'
      fullPath: '/kotdwar-to-jim-corbett-taxi'
      preLoaderRoute: typeof KotdwarToJimCorbettTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-kedarnath-taxi': {
      id: '/kotdwar-to-kedarnath-taxi'
      path: '/kotdwar-to-kedarnath-taxi'
      fullPath: '/kotdwar-to-kedarnath-taxi'
      preLoaderRoute: typeof KotdwarToKedarnathTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-lansdowne-taxi': {
      id: '/kotdwar-to-lansdowne-taxi'
      path: '/kotdwar-to-lansdowne-taxi'
      fullPath: '/kotdwar-to-lansdowne-taxi'
      preLoaderRoute: typeof KotdwarToLansdowneTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-mussoorie-taxi': {
      id: '/kotdwar-to-mussoorie-taxi'
      path: '/kotdwar-to-mussoorie-taxi'
      fullPath: '/kotdwar-to-mussoorie-taxi'
      preLoaderRoute: typeof KotdwarToMussoorieTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-nainital-taxi': {
      id: '/kotdwar-to-nainital-taxi'
      path: '/kotdwar-to-nainital-taxi'
      fullPath: '/kotdwar-to-nainital-taxi'
      preLoaderRoute: typeof KotdwarToNainitalTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-rishikesh-taxi': {
      id: '/kotdwar-to-rishikesh-taxi'
      path: '/kotdwar-to-rishikesh-taxi'
      fullPath: '/kotdwar-to-rishikesh-taxi'
      preLoaderRoute: typeof KotdwarToRishikeshTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotdwar-to-yamunotri-taxi': {
      id: '/kotdwar-to-yamunotri-taxi'
      path: '/kotdwar-to-yamunotri-taxi'
      fullPath: '/kotdwar-to-yamunotri-taxi'
      preLoaderRoute: typeof KotdwarToYamunotriTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outstation-taxi': {
      id: '/outstation-taxi'
      path: '/outstation-taxi'
      fullPath: '/outstation-taxi'
      preLoaderRoute: typeof OutstationTaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-service': {
      id: '/taxi-service'
      path: '/taxi-service'
      fullPath: '/taxi-service'
      preLoaderRoute: typeof TaxiServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AirportTaxiRoute: AirportTaxiRoute,
  CharDhamYatraRoute: CharDhamYatraRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  KotdwarToBadrinathTaxiRoute: KotdwarToBadrinathTaxiRoute,
  KotdwarToDehradunTaxiRoute: KotdwarToDehradunTaxiRoute,
  KotdwarToDelhiTaxiRoute: KotdwarToDelhiTaxiRoute,
  KotdwarToGangotriTaxiRoute: KotdwarToGangotriTaxiRoute,
  KotdwarToHaridwarTaxiRoute: KotdwarToHaridwarTaxiRoute,
  KotdwarToJimCorbettTaxiRoute: KotdwarToJimCorbettTaxiRoute,
  KotdwarToKedarnathTaxiRoute: KotdwarToKedarnathTaxiRoute,
  KotdwarToLansdowneTaxiRoute: KotdwarToLansdowneTaxiRoute,
  KotdwarToMussoorieTaxiRoute: KotdwarToMussoorieTaxiRoute,
  KotdwarToNainitalTaxiRoute: KotdwarToNainitalTaxiRoute,
  KotdwarToRishikeshTaxiRoute: KotdwarToRishikeshTaxiRoute,
  KotdwarToYamunotriTaxiRoute: KotdwarToYamunotriTaxiRoute,
  OutstationTaxiRoute: OutstationTaxiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxiServiceRoute: TaxiServiceRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
